### ISSUE TITLE
Create UI

### ISSUE THREAD

**Issue by teymour-aldridge** [MLH-Fellowship/0.5.1-household-client#2]
I think we should create the UI using the [React Material Web Components](https://rmwc.io/) library for simplicity and speed. @victorphoenix3 has a [suggested layout for how things should look](https://github.com/MLH-Fellowship/0.5.1-household/issues/2) which I think is good.

**Comment by teymour-aldridge** [comment]
@tayoogunbiyi do you want to do this?

**Comment by tayoogunbiyi** [comment]
yes. I would do it

**Comment by tayoogunbiyi** [comment]
but would like to clarify some specifics before starting [regarding the suggested layout for how things would looks](https://github.com/MLH-Fellowship/0.5.1-household/issues/2)

**Comment by teymour-aldridge** [comment]
Sounds like a plan!
